### ISSUE TITLE
window is not defined on require

### ISSUE THREAD

**Issue by nicholas-johnson** [BeneathTheInk/html2md#1]
Currently getting an error when requiring this in node. It looks like it's coming from the bti-dom-utils module:

```
var html2md = require('html2md');
```

stack trace:

```
ReferenceError: window is not defined
    at Object.<anonymous>     (/Users/nicholas/Dropbox/code/higgidy_node/node_modules/html2md/node_modules/bti-dom-utils/index.js:105:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous>     (/Users/nicholas/Dropbox/code/higgidy_node/node_modules/html2md/lib/html2md.js:15:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by Ohar** [comment]
Not supporting NodeJS
